spring.application.name=user-service

spring.data.jdbc.dialect=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create-drop

logging.level.web=DEBUG
logging.level.sql=DEBUG


jwt.secret=SECRET
